# 服务端口
server:
  port: 8202


spring:
  application:
    #服务名
    name: service-cmn
    # 环境设置：dev、test、prod
  profiles:
    active: dev
    # mysql数据库连接
  datasource:
    username: zcc
    password: 3er4#ER$
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://zccgrzyxm.rwlb.rds.aliyuncs.com:5432/yygh_cmn?characterEncoding=utf-8&useSSL=false

    #返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  banner:
    location: classpath:banner.txt
#    redis配置
  redis:
    host: 8.136.219.183
    port: 6379
    password: 3er4#ER$
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0
#mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.commons.JakartaCommonsLoggingImpl
