# 服务端口
server:
  port: 8202


spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    #服务名
    name: service-cmn
    # 环境设置：dev、test、prod
  profiles:
    active: dev
    # mysql数据库连接
  datasource:
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://112.124.24.3:7001/yygh_cmn?characterEncoding=utf-8&useSSL=false
    hikari:
      max-lifetime: 500000


    #返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  #    redis配置
  redis:
    host: 112.124.24.3
    port: 7002
    password: 3er4#ER$
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0
#mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.commons.JakartaCommonsLoggingImpl
