#服务端口
server:
  port: 8080
spring:
  # 服务名
  application:
    name: service-gateway
  cloud:
    # nacos服务地址
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      #使用服务发现路由
      discovery:
        locator:
          enabled: true
      routes[0]:
        #设置路由id
        id: service-hosp
        #设置路由的uri
        uri: lb://service-hosp
        #设置路由断言,代理servicerId为auth-service的/auth/路径
        predicates: Path=/*/hosp/**
      routes[1]:
        #设置路由id
        id: service-cmn
        #        设置路由的uri
        uri: lb://service-cmn
        #设置路由断言,代理servicerId为auth-service的/auth/路径
        predicates: Path=/*/cmn/**
        routes[2]:
          #设置路由id
          id: service-user
          #        设置路由的uri
          uri: lb://service-user
          #设置路由断言,代理servicerId为auth-service的/auth/路径
          predicates: Path=/*/user/**
          routes[3]:
            #设置路由id
            id: service-msm
            #        设置路由的uri
            uri: lb://service-msm
            #设置路由断言,代理servicerId为auth-service的/auth/路径
            predicates: Path=/*/msm/**



